export const ENDPOINTS = {
    AUTH: 'auth',
    TABS: 'tabs',
    APP: 'app',
    ABSENCE: 'absences',
    BUSES: 'buses',
    CONTACTS: 'contacts',
    HOME: 'home',
    NOTIFICATIONS: 'notifications',
    PICKUP: 'pickup',
    PROFILE: 'profile',
    QUESTION_NEW: 'questions/new',
    QUESTIONS: 'questions',
    SCHEDULE: 'schedule',
    STUDENTS: 'students',
    SURVEYS: 'surveys',
    ABSENCE_REPORT: 'absence-report'
};

const ROOT = '/app/tabs/';
export const FULL_ROUTES = {
    APP: ENDPOINTS.APP,
    AUTH: ENDPOINTS.AUTH,
    TABS: ENDPOINTS.TABS,
    HOME: ROOT + ENDPOINTS.HOME,
    STUDENTS: ROOT + ENDPOINTS.STUDENTS,
    ABSENCE: ROOT + ENDPOINTS.ABSENCE,
    PICKUP: ROOT + ENDPOINTS.PICKUP,
    BUSES: ROOT + ENDPOINTS.BUSES,
    CONTACTS: ROOT + ENDPOINTS.CONTACTS,
    NOTIFICATIONS: ROOT + ENDPOINTS.NOTIFICATIONS,
    PROFILE: ROOT + ENDPOINTS.PROFILE,
    QUESTIONS: ROOT + ENDPOINTS.QUESTIONS,
    QUESTION_NEW: ROOT + ENDPOINTS.QUESTION_NEW,
    SCHEDULE: ROOT + ENDPOINTS.SCHEDULE,
    SURVEYS: ROOT + ENDPOINTS.SURVEYS,
    FORM_ABSENCE_REPORT: ROOT + ENDPOINTS.ABSENCE + '/' + ENDPOINTS.ABSENCE_REPORT,
    STUDENT_ABSENCE_REPORT: ROOT + ENDPOINTS.STUDENTS + '/' + ENDPOINTS.ABSENCE_REPORT
};
